"""Convert ~/riscv-tools/artifacts/block3_export.npz into static C header files for bare-metal use."""
import numpy as np
import os

DATA = np.load(os.path.expanduser("~/riscv-tools/artifacts/block3_export.npz"))
OUT_DIR = "/mnt/d/000_CAOHOC/NTHU_Courses/Advanced Computer Architecture/Project/src/model_data"


def c_array(name, arr, ctype):
    flat = arr.flatten()
    body = ", ".join(str(int(v)) for v in flat)
    return f"static const {ctype} {name}[{flat.size}] = {{ {body} }};\n"


def main():
    import os
    os.makedirs(OUT_DIR, exist_ok=True)

    d = DATA
    lines = []
    lines.append("/* Auto-generated by scripts/model_prep/export_to_c.py. Do not edit by hand. */")
    lines.append("#ifndef BLOCK3_PARAMS_H")
    lines.append("#define BLOCK3_PARAMS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/* Shapes: expand 24->72 (1x1), depthwise 72ch (3x3, pad1), project 72->24 (1x1) */")
    lines.append("#define BLOCK3_CIN   24")
    lines.append("#define BLOCK3_MID   72")
    lines.append("#define BLOCK3_H     56")
    lines.append("#define BLOCK3_W     56")
    lines.append("")
    lines.append(f"#define BLOCK3_ZP_IN   {int(d['zp_in'])}")
    lines.append(f"#define BLOCK3_ZP_MID0 {int(d['zp_mid0'])}")
    lines.append(f"#define BLOCK3_ZP_MID1 {int(d['zp_mid1'])}")
    lines.append(f"#define BLOCK3_ZP_MID2 {int(d['zp_mid2'])}")
    lines.append(f"#define BLOCK3_ZP_OUT  {int(d['zp_out'])}")
    lines.append("")
    lines.append(c_array("block3_w0_q", d["w0_q"], "int8_t"))    # (72,24,1,1)
    lines.append(c_array("block3_b0_q", d["b0_q"], "int32_t"))
    lines.append(c_array("block3_m0_fixed", d["m0_fixed"], "int32_t"))
    lines.append(c_array("block3_m0_shift", d["m0_shift"], "int32_t"))
    lines.append("")
    lines.append(c_array("block3_w1_q", d["w1_q"], "int8_t"))    # (72,1,3,3)
    lines.append(c_array("block3_b1_q", d["b1_q"], "int32_t"))
    lines.append(c_array("block3_m1_fixed", d["m1_fixed"], "int32_t"))
    lines.append(c_array("block3_m1_shift", d["m1_shift"], "int32_t"))
    lines.append("")
    lines.append(c_array("block3_w2_q", d["w2_q"], "int8_t"))    # (24,72,1,1)
    lines.append(c_array("block3_b2_q", d["b2_q"], "int32_t"))
    lines.append(c_array("block3_m2_fixed", d["m2_fixed"], "int32_t"))
    lines.append(c_array("block3_m2_shift", d["m2_shift"], "int32_t"))
    lines.append("")
    lines.append(f"#define BLOCK3_ADD_MULT_A {int(d['add_mult_a'])}")
    lines.append(f"#define BLOCK3_ADD_SHIFT_A {int(d['add_shift_a'])}")
    lines.append(f"#define BLOCK3_ADD_MULT_B {int(d['add_mult_b'])}")
    lines.append(f"#define BLOCK3_ADD_SHIFT_B {int(d['add_shift_b'])}")
    lines.append("")
    lines.append("#endif /* BLOCK3_PARAMS_H */")

    with open(f"{OUT_DIR}/block3_params.h", "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    golden = [
        "/* Auto-generated by scripts/model_prep/export_to_c.py. Do not edit by hand. */",
        "#ifndef BLOCK3_GOLDEN_H",
        "#define BLOCK3_GOLDEN_H",
        "",
        "#include <stdint.h>",
        "",
        c_array("block3_test_input", d["x_int"], "int8_t"),    # (24,56,56)
        c_array("block3_golden_output", d["final_int"], "int8_t"),  # (24,56,56)
        "",
        "#endif /* BLOCK3_GOLDEN_H */",
    ]
    with open(f"{OUT_DIR}/block3_golden.h", "w", newline="\n") as f:
        f.write("\n".join(golden) + "\n")

    print("Wrote", f"{OUT_DIR}/block3_params.h")
    print("Wrote", f"{OUT_DIR}/block3_golden.h")


if __name__ == "__main__":
    main()
